LANGUAGES = ['aa',
             'ab',
             'af',
             'ak',
             'sq',
             'am',
             'ar',
             'an',
             'hy',
             'as',
             'av',
             'ae',
             'ay',
             'az',
             'ba',
             'bm',
             'eu',
             'be',
             'bn',
             'bh',
             'bi',
             'bo',
             'bs',
             'br',
             'bg',
             'my',
             'ca',
             'cs',
             'ch',
             'ce',
             'zh',
             'cu',
             'cv',
             'kw',
             'co',
             'cr',
             'cy',
             'cs',
             'da',
             'de',
             'dv',
             'nl',
             'dz',
             'el',
             'en',
             'eo',
             'et',
             'eu',
             'ee',
             'fo',
             'fa',
             'fj',
             'fi',
             'fr',
             'fy',
             'ff',
             'Ga',
             'de',
             'gd',
             'ga',
             'gl',
             'gv',
             'el',
             'gn',
             'gu',
             'ht',
             'ha',
             'he',
             'hz',
             'hi',
             'ho',
             'hr',
             'hu',
             'hy',
             'ig',
             'is',
             'io',
             'ii',
             'iu',
             'ie',
             'ia',
             'id',
             'ik',
             'is',
             'it',
             'jv',
             'ja',
             'kl',
             'kn',
             'ks',
             'ka',
             'kr',
             'kk',
             'km',
             'ki',
             'rw',
             'ky',
             'kv',
             'kg',
             'ko',
             'kj',
             'ku',
             'lo',
             'la',
             'lv',
             'li',
             'ln',
             'lt',
             'lb',
             'lu',
             'lg',
             'mk',
             'mh',
             'ml',
             'mi',
             'mr',
             'ms',
             'Mi',
             'mk',
             'mg',
             'mt',
             'mn',
             'mi',
             'ms',
             'my',
             'na',
             'nv',
             'nr',
             'nd',
             'ng',
             'ne',
             'nl',
             'nn',
             'nb',
             'no',
             'oc',
             'oj',
             'or',
             'om',
             'os',
             'pa',
             'fa',
             'pi',
             'pl',
             'pt',
             'ps',
             'qu',
             'rm',
             'ro',
             'ro',
             'rn',
             'ru',
             'sg',
             'sa',
             'si',
             'sk',
             'sk',
             'sl',
             'se',
             'sm',
             'sn',
             'sd',
             'so',
             'st',
             'es',
             'sq',
             'sc',
             'sr',
             'ss',
             'su',
             'sw',
             'sv',
             'ty',
             'ta',
             'tt',
             'te',
             'tg',
             'tl',
             'th',
             'bo',
             'ti',
             'to',
             'tn',
             'ts',
             'tk',
             'tr',
             'tw',
             'ug',
             'uk',
             'ur',
             'uz',
             've',
             'vi',
             'vo',
             'cy',
             'wa',
             'wo',
             'xh',
             'yi',
             'yo',
             'za',
             'zh',
             'zu'
             ]

PERIODIC_TAB_FR = {
    'H': 'Hydrogène',
    'He': 'Hélium',
    'Li': 'Lithium',
    'Be': 'Béryllium',
    'B': 'Bore',
    'C': 'Carbone',
    'N': 'Azote',
    'O': 'Oxygène',
    'F': 'Fluor',
    'Ne': 'Néon',
    'Na': 'Sodium',
    'Mg': 'Magnésium',
    'Al': 'Aluminium',
    'Si': 'Silicium',
    'P': 'Phosphore',
    'S': 'Soufre',
    'Cl': 'Chlore',
    'Ar': 'Argon',
    'K': 'Potassium',
    'Ca': 'Calcium',
    'Sc': 'Scandium',
    'Ti': 'Titane',
    'V': 'Vanadium',
    'Cr': 'Chrome',
    'Mn': 'Manganèse',
    'Fe': 'Fer',
    'Ni': 'Nickel',
    'Co': 'Cobalt',
    'Cu': 'Cuivre',
    'Zn': 'Zinc',
    'Ga': 'Gallium',
    'Ge': 'Germanium',
    'As': 'Arsenic',
    'Se': 'Sélénium',
    'Br': 'Brome',
    'Kr': 'Krypton',
    'Rb': 'Rubidium',
    'Sr': 'Strontium',
    'Y': 'Yttrium',
    'Zr': 'Zirconium',
    'Nb': 'Niobium',
    'Mo': 'Molybdène',
    'Tc': 'Technétium',
    'Ru': 'Ruthénium',
    'Rh': 'Rhodium',
    'Pd': 'Palladium',
    'Ag': 'Argent',
    'Cd': 'Cadmium',
    'In': 'Indium',
    'Sn': 'Étain',
    'Sb': 'Antimoine',
    'I': 'Iode',
    'Te': 'Tellure',
    'Xe': 'Xénon',
    'Cs': 'Césium',
    'Ba': 'Barium',
    'La': 'Lanthane',
    'Ce': 'Cérium',
    'Pr': 'Praséodyme',
    'Nd': 'Néodyme',
    'Pm': 'Prométhium',
    'Sm': 'Samarium',
    'Eu': 'Europium',
    'Gd': 'Gadolinium',
    'Tb': 'Terbium',
    'Dy': 'Dysprosium',
    'Ho': 'Holmium',
    'Er': 'Erbium',
    'Tm': 'Thulium',
    'Yb': 'Ytterbium',
    'Lu': 'Lutécium',
    'Hf': 'Hafnium',
    'Ta': 'Tantale',
    'W': 'Tungstène',
    'Re': 'Rhénium',
    'Os': 'Osmium',
    'Ir': 'Iridium',
    'Pt': 'Platine',
    'Au': 'Or',
    'Hg': 'Mercure',
    'Tl': 'Thallium',
    'Pb': 'Plomb',
    'Bi': 'Bismuth',
    'Po': 'Polonium',
    'At': 'Astate',
    'Rn': 'Radon',
    'Fr': 'Francium',
    'Ra': 'Radium',
    'Ac': 'Actinium',
    'Th': 'Thorium',
    'Pa': 'Protactinium',
    'U': 'Uranium',
    'Np': 'Neptunium',
    'Pu': 'Plutonium',
    'Am': 'Américium',
    'Cm': 'Curium',
    'Bk': 'Berkélium',
    'Cf': 'Californium',
    'Es': 'Einsteinium',
    'Fm': 'Fermium',
    'Md': 'Mendélévium',
    'No': 'Nobélium',
    'Lr': 'Lawrencium',
    'Rf': 'Rutherfordium',
    'Db': 'Dubnium',
    'Sg': 'Seaborgium',
    'Bh': 'Bohrium',
    'Hs': 'Hassium',
    'Mt': 'Meitnérium',
    'Ds': 'Darmstadtium',
    'Rg': 'Roentgenium',
    'Cn': 'Copernicium',
    'Nh': 'Nihonium',
    'Fl': 'Flerovium',
    'Mc': 'Moscovium',
    'Lv': 'Livermorium',
    'Ts': 'Tennessine',
    'Og': 'Oganesson'
}

PERIODIC_TAB_EN = {
    'H': 'Hydrogen',
    'He': 'Helium',
    'Li': 'Lithium',
    'Be': 'Beryllium',
    'B': 'Boron',
    'C': 'Carbon',
    'N': 'Nitrogen',
    'O': 'Oxygen',
    'F': 'Fluorine',
    'Ne': 'Neon',
    'Na': 'Sodium',
    'Mg': 'Magnesium',
    'Al': 'Aluminum',
    'Si': 'Silicon',
    'P': 'Phosphorus',
    'S': 'Sulfur',
    'Cl': 'Chlorine',
    'Ar': 'Argon',
    'K': 'Potassium',
    'Ca': 'Calcium',
    'Sc': 'Scandium',
    'Ti': 'Titanium',
    'V': 'Vanadium',
    'Cr': 'Chromium',
    'Mn': 'Manganese',
    'Fe': 'Iron',
    'Ni': 'Nickel',
    'Co': 'Cobalt',
    'Cu': 'Copper',
    'Zn': 'Zinc',
    'Ga': 'Gallium',
    'Ge': 'Germanium',
    'As': 'Arsenic',
    'Se': 'Selenium',
    'Br': 'Bromine',
    'Kr': 'Krypton',
    'Rb': 'Rubidium',
    'Sr': 'Strontium',
    'Y': 'Yttrium',
    'Zr': 'Zirconium',
    'Nb': 'Niobium',
    'Mo': 'Molybdenum',
    'Tc': 'Technetium',
    'Ru': 'Ruthenium',
    'Rh': 'Rhodium',
    'Pd': 'Palladium',
    'Ag': 'Silver',
    'Cd': 'Cadmium',
    'In': 'Indium',
    'Sn': 'Tin',
    'Sb': 'Antimony',
    'I': 'Iodine',
    'Te': 'Tellurium',
    'Xe': 'Xenon',
    'Cs': 'Cesium',
    'Ba': 'Barium',
    'La': 'Lanthanum',
    'Ce': 'Cerium',
    'Pr': 'Praseodymium',
    'Nd': 'Neodymium',
    'Pm': 'Promethium',
    'Sm': 'Samarium',
    'Eu': 'Europium',
    'Gd': 'Gadolinium',
    'Tb': 'Terbium',
    'Dy': 'Dysprosium',
    'Ho': 'Holmium',
    'Er': 'Erbium',
    'Tm': 'Thulium',
    'Yb': 'Ytterbium',
    'Lu': 'Lutetium',
    'Hf': 'Hafnium',
    'Ta': 'Tantalum',
    'W': 'Tungsten',
    'Re': 'Rhenium',
    'Os': 'Osmium',
    'Ir': 'Iridium',
    'Pt': 'Platinum',
    'Au': 'Gold',
    'Hg': 'Mercury',
    'Tl': 'Thallium',
    'Pb': 'Lead',
    'Bi': 'Bismuth',
    'Po': 'Polonium',
    'At': 'Astatine',
    'Rn': 'Radon',
    'Fr': 'Francium',
    'Ra': 'Radium',
    'Ac': 'Actinium',
    'Th': 'Thorium',
    'Pa': 'Protactinium',
    'U': 'Uranium',
    'Np': 'Neptunium',
    'Pu': 'Plutonium',
    'Am': 'Americium',
    'Cm': 'Curium',
    'Bk': 'Berkelium',
    'Cf': 'Californium',
    'Es': 'Einsteinium',
    'Fm': 'Fermium',
    'Md': 'Mendelevium',
    'No': 'Nobelium',
    'Lr': 'Lawrencium',
    'Rf': 'Rutherfordium',
    'Db': 'Dubnium',
    'Sg': 'Seaborgium',
    'Bh': 'Bohrium',
    'Hs': 'Hassium',
    'Mt': 'Meitnerium',
    'Ds': 'Darmstadtium',
    'Rg': 'Roentgenium',
    'Cn': 'Copernicium',
    'Nh': 'Nihonium',
    'Fl': 'Flerovium',
    'Mc': 'Moscovium',
    'Lv': 'Livermorium',
    'Ts': 'Tennessine',
    'Og': 'Oganesson'
}
