USEFULL_CSV = ['Basis of Record',
 'Catalog Number',
 'Collection Code',
 'Collection ID',
 'Collection Name',
 'DWCA ID',
 'Family',
 'Genus',
 'Institution Code',
 'Institution ID',
 'Institution Name',
 'Modified',
 'Scientific Name',
 'Specific Epithet',
 'Collector name',
 'Collect number',
 'Date of collect',
 'Latitude',
 'Longitude',
 'Created',
 'Family',
 'Genus',
 'Higher Classification',
 'Identification Verification Status',
 'Modified',
 'Scientific Name',
 'Scientific Name Authorship',
 'Specific Epithet',
 'Taxon ID',
 'Catalog Number',
 'Family',
 'Genus',
 'Scientific name',
 'Collection number',
 'Title',
 'Creator',
 'Subject/Keywords',
 'Description',
 'Publisher',
 'Contributor',
 'Date',
 'Identifier',
 'Source',
 'Language',
 'Relation',
 'Coverage / place',
 'Rights Usage Terms',
 'Contact',
 'Orientation']

