label: MS 59 Avranches - analyses physico-chimique @CRC
manifest: MS_59_Avranches_CRC
description: test bidule

Institution:
  - label: Centre de la Recherche sur la Conservations
    homepage: https://crc.mnhn.fr/fr
  - label: Museum nationale d'Histoire Naturelle
    homepage: None
  - label: Centre de la Recherche sur la Conservation
    homepage: https://www.cnrs.fr/fr
    
metadata:
    data-source:
      - url: https://doi.org/10.48579/PRO/CM1FLM
    technique:
      - label: XRF
      - label: Hyperspecral

authors:
  - name: Michelin
    forename: Anne
    role: Maîtresse de conférence
  - name: Robinet
    forename: None
    role: Ingénieur de recherche
    
licence:
  label: Etalab 2.0
  attribution: <span>Centre de la Recherche sur la Conservation. <a href=\"https://spdx.org/licenses/etalab-2.0.html\">OPEN LICENCE 2.0</a> <a href=\"https://spdx.org/licenses/etalab-2.0.html\" title\"Etalab 2.0\"><img src=\"https://www.etalab.gouv.fr/wp-content/uploads/2011/10/licence-ouverte-open-licence.gif\"/></a></span>
  link: https://spdx.org/licenses/etalab-2.0.html
  logo: https://www.etalab.gouv.fr/wp-content/uploads/2011/10/licence-ouverte-open-licence.gif

